using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;

namespace StoneForge.Generators;

// What every generated file shares: C# names from the game's, the header, escaping, and reading the dump.
internal static class Emit
{
    private static readonly HashSet<string> Keywords = new()
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class", "const", "continue",
        "decimal", "default", "delegate", "do", "double", "else", "enum", "event", "explicit", "extern", "false", "finally",
        "fixed", "float", "for", "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params", "private", "protected",
        "public", "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string",
        "struct", "switch", "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort",
        "using", "virtual", "void", "volatile", "while",
    };

    /// <summary>A game name as a C# identifier: other characters as _, a leading digit prefixed, a keyword as @name.</summary>
    public static string Ident(string name)
    {
        string id = Regex.Replace(name, "[^A-Za-z0-9_]", "_");
        if (id.Length == 0 || char.IsDigit(id[0]))
            id = "_" + id;
        return Keywords.Contains(id) ? "@" + id : id;
    }

    /// <summary>The top of a generated file.</summary>
    public static string Header(string what) =>
        $"// <auto-generated> by StoneForge.Generators from the game's data (StoneForge.DataDump's dump of this machine's Stoneshard): {what}.\n#nullable enable\n#pragma warning disable CS1591\n";

    /// <summary>A C# string literal.</summary>
    public static string Literal(string s) => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    /// <summary>Text for an XML doc comment.</summary>
    public static string Xml(string s) => s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    /// <summary>A .tsv dump's records: its non-blank lines, split at tabs.</summary>
    public static IEnumerable<string[]> Rows(string text) => Lines(text).Select(l => l.Split('\t'));

    /// <summary>A dump's non-blank lines.</summary>
    public static IEnumerable<string> Lines(string? text) => text == null ? Enumerable.Empty<string>()
        : text.Split('\n').Select(l => l.TrimEnd('\r')).Where(l => l.Length > 0);
}
